export const GET_EVALUATION_SCALE_PROGRESS = 'GET_DATA_EVALUATION_SCALE_PROGRESS';
export const GET_EVALUATION_SCALE_SUCCESS = 'GET_DATA_EVALUATION_SCALE_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_EVALUATION_SCALE = 'ADD_EVALUATION_SCALE';
export const UPDATE_EVALUATION_SCALE = 'UPDATE_EVALUATION_SCALE';
export const DELETE_EVALUATION_SCALE = 'DELETE_EVALUATION_SCALE';
export const SEARCH_EVALUATION_SCALE = 'SEARCH_EVALUATION_SCALE';
