export const GET_SERVICE_PROGRESS = 'GET_DATA_SERVICE_PROGRESS';
export const GET_SERVICE_SUCCESS = 'GET_DATA_SERVICE_SUCCESS';
export const GET_ITEM_BY_SERVICE_SUCCESS = 'GET_ITEM_BY_SERVICE_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_SERVICE = 'ADD_SERVICE';
export const SAVE_SERVICE = 'SAVE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const ADD_ITEM = 'ADD_ITEM';
export const SAVE_ITEM = 'SAVE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const SEARCH_ITEM = 'SEARCH_ITEM';
export const COLLAPSE_SERVICE = 'COLLAPSE_SERVICE';

