export const GET_DATA_SURVEY_ADMON_PROGRESS = 'GET_DATA_SURVEY_ADMON_PROGRESS';
export const GET_DATA_SURVEY_ADMON_SUCCESS = 'GET_DATA_SURVEY_ADMON_SUCCESS';

export const GET_SURVEY_ADMON_PROGRESS = 'GET_SURVEY_ADMON_PROGRESS';
export const GET_SURVEY_ADMON_SUCCESS = 'GET_SURVEY_ADMON_SUCCESS';

export const GET_ADD_SURVEY_ADMON = 'GET_ADD_SURVEY_ADMON';
export const SEARCH_SURVEY_ADMON = 'SEARCH_SURVEY_ADMON';
export const CHANGE_SEARCH_SURVEY_ADMON = 'CHANGE_SEARCH_SURVEY_ADMON';
export const SAVE_SURVEY_ADMON = 'SAVE_SURVEY_ADMON';
export const DELETE_SURVEY_ADMON = 'DELETE_SURVEY_ADMON';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT_SURVEY_ADMON = 'CLEAR_EDIT_SURVEY_ADMON';
export const CHANGE_DISABLED_SURVEY_ADMON = 'CHANGE_DISABLED_SURVEY_ADMON';
