export const GET_DATA_QUESTION_PROGRESS = 'GET_DATA_QUESTION_PROGRESS';
export const GET_DATA_QUESTION_SUCCESS = 'GET_DATA_QUESTION_SUCCESS';

export const GET_QUESTION_PROGRESS = 'GET_QUESTION_PROGRESS';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';

export const GET_OPTIONS_BY_QUESTION = 'GET_OPTIONS_BY_QUESTION';
export const GET_ADD_QUESTION = 'GET_ADD_QUESTION';

export const SEARCH_QUESTION = 'SEARCH_QUESTION';
export const CHANGE_SEARCH_QUESTION = 'CHANGE_SEARCH_QUESTION';
export const CHANGE_ANSWER_TYPE = 'CHANGE_ANSWER_TYPE';
export const CHANGE_DEPENDING_QUESTION = 'CHANGE_DEPENDING_QUESTION';
export const CHANGE_ITEMS = 'CHANGE_ITEMS';
export const CHANGE_DIMENSION = 'CHANGE_DIMENSION';
export const CHANGE_CRITERION = 'CHANGE_CRITERION';
export const CHANGE_HELP_TEXT = 'CHANGE_HELP_TEXT';
export const CHANGE_QUESTION = 'CHANGE_QUESTION';
export const SWITCH_REQUIRED = 'SWITCH_REQUIRED';
export const SWITCH_REQUIRED_ATTACHMENT = 'SWITCH_REQUIRED_ATTACHMENT';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';

export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_DATA_OPTION = 'SAVE_DATA_OPTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT = 'CLEAR_EDIT';
export const CHANGE_DISABLED = 'CHANGE_DISABLED';
