export const GET_DATA_SURVEY_ADMON_PROGRESS = 'GET_DATA_SURVEY_ADMON_PROGRESS';
export const GET_DATA_SURVEY_ADMON_SUCCESS = 'GET_DATA_SURVEY_ADMON_SUCCESS';

export const GET_SURVEY_ADMON_PROGRESS = 'GET_SURVEY_ADMON_PROGRESS';
export const GET_SURVEY_ADMON_SUCCESS = 'GET_SURVEY_ADMON_SUCCESS';

export const GET_QUESTIONS_BY_DIMENSION = 'GET_QUESTIONS_BY_DIMENSION';

export const GET_ADD_SURVEY_ADMON = 'GET_ADD_SURVEY_ADMON';
export const COLLAPSE_DIMENSION_SURVEY_FORM = 'COLLAPSE_DIMENSION_SURVEY_FORM';
export const COLLAPSE_CRITERION_SURVEY_FORM = 'COLLAPSE_CRITERION_SURVEY_FORM';
export const SEARCH_SURVEY_ADMON = 'SEARCH_SURVEY_ADMON';
export const CHANGE_SEARCH_SURVEY_ADMON = 'CHANGE_SEARCH_SURVEY_ADMON';
export const SAVE_SURVEY_ADMON = 'SAVE_SURVEY_ADMON';
export const DELETE_SURVEY_ADMON = 'DELETE_SURVEY_ADMON';
export const CLEAN_DATA = 'CLEAN_DATA';
export const SEARCH_BY_DIMENSION = 'SEARCH_BY_DIMENSION';
export const CHANGE_SEARCH_BY_DIMENSION = 'CHANGE_SEARCH_BY_DIMENSION';
export const SEARCH_QUESTION_SURVEY = 'SEARCH_QUESTION_SURVEY';
export const CHANGE_SEARCH_BY_QUESTION_SURVEY = 'CHANGE_SEARCH_BY_QUESTION_SURVEY';
export const SAVE_QUESTION_SELECTED = 'SAVE_QUESTION_SELECTED';
export const FILTER_CRITERION_SURVEY = 'FILTER_CRITERION_SURVEY';
export const DIMENSION_DESELECTED = 'DIMENSION_DESELECTED';
export const FILTER_BY_CRITERION_SURVEY = 'FILTER_BY_CRITERION_SURVEY';

export const GET_DIMENSIONS_SURVEY_SUCCESS = 'GET_DIMENSIONS_SURVEY_SUCCESS';
export const GET_DIMENSIONS_SURVEY_PROGRESS = 'GET_DIMENSIONS_SURVEY_PROGRESS';
export const GET_CRITERION_SURVEY_SUCCESS = 'GET_CRITERION_SURVEY_SUCCESS';
export const COMPANY_SIZE_VALUE = 'COMPANY_SIZE_VALUE';
export const SUPPLY_VALUE = 'SUPPLY_VALUE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT_SURVEY_ADMON = 'CLEAR_EDIT_SURVEY_ADMON';
export const CHANGE_DISABLED_SURVEY_ADMON = 'CHANGE_DISABLED_SURVEY_ADMON';
