export const GET_MANAGER_TEAM_SURVEY_PROGRESS = 'GET_MANAGER_TEAM_SURVEY_PROGRESS';
export const GET_MANAGER_TEAM_SURVEY_SUCCESS = 'GET_MANAGER_TEAM_SURVEY_SUCCESS';
export const FILTER_MANAGER_TEAM_SURVEY = 'FILTER_MANAGER_TEAM_SURVEY';
export const CHANGE_ANSWER = 'CHANGE_ANSWER';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
export const UPDATE_SUPPLIERS = 'UPDATE_SUPPLIERS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
