export const GET_MANAGER_TEAM_SURVEY_PROGRESS = 'GET_MANAGER_TEAM_SURVEY_PROGRESS';
export const GET_MANAGER_TEAM_SURVEY_SUCCESS = 'GET_MANAGER_TEAM_SURVEY_SUCCESS';
export const FILTER_MANAGER_TEAM_SURVEY = 'FILTER_MANAGER_TEAM_SURVEY';
export const CHANGE_SCORE_MANAGER = 'CHANGE_SCORE_MANAGER';
export const CHANGE_COMMENT_MANAGER = 'CHANGE_COMMENT_MANAGER';
export const UPDATE_ERRORS_MANAGER = 'UPDATE_ERRORS_MANAGER';
export const UPDATE_SUPPLIERS_MANAGER = 'UPDATE_SUPPLIERS_MANAGER';
export const REQUEST_FAILED = 'REQUEST_FAILED';
