export const GET_ENDED_EVALUATOR_PROGRESS = 'GET_ENDED_EVALUATOR_PROGRESS';
export const GET_ENDED_EVALUATOR_SUCCESS = 'GET_ENDED_EVALUATOR_SUCCESS';
export const CHECK_SUPPLIER = 'CHECK_SUPPLIER';
export const UPDATE_ENDED_EVALUATOR = 'UPDATE_ENDED_EVALUATOR';
export const REQUEST_FAILED = 'REQUEST_FAILED';
