export const GET_ALERT_PROGRESS = 'GET_DATA_ALERT_PROGRESS';
export const GET_ALERT_SUCCESS = 'GET_DATA_ALERT_SUCCESS';

export const SAVE_ALERT = 'ADD_ALERT';

export const REQUEST_FAILED = 'REQUEST_FAILED';
