export const GET_DATA_PENDINGS_PROGRESS = 'GET_DATA_PENDINGS_PROGRESS';
export const GET_DATA_PENDINGS_SUCCESS = 'GET_DATA_PENDINGS_SUCCESS';
export const FILTER_PENDINGS = 'FILTER_PENDINGS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
