export const GET_DATA_SUPPLIER_REPORT_PROGRESS = 'GET_DATA_SUPPLIER_REPORT_PROGRESS';
export const GET_DATA_SUPPLIER_REPORT_SUCCESS = 'GET_DATA_SUPPLIER_REPORT_SUCCESS';
export const GET_DATA_DIMENSIONS = 'GET_DATA_DIMENSIONS';
export const FILTER_SUPPLIER_REPORT = 'FILTER_SUPPLIER_REPORT';
export const REQUEST_FAILED = 'REQUEST_FAILED';
