export const GET_USER_CONTEXT_PROGRESS = 'GET_USER_CONTEXT_PROGRESS';
export const GET_USER_CONTEXT_SUCCESS = 'GET_USER_CONTEXT_SUCCESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const LOADING_MODAL = 'LOADING_MODAL';

