export const GET_DATA_CALL_REPORT_PROGRESS = 'GET_DATA_CALL_REPORT_PROGRESS';
export const GET_DATA_CALL_REPORT_SUCCESS = 'GET_DATA_CALL_REPORT_SUCCESS';
export const FILTER_CALL_REPORT = 'FILTER_CALL_REPORT';
export const REQUEST_FAILED = 'REQUEST_FAILED';
