export const GET_SECTOR_PROGRESS = 'GET_DATA_SECTOR_PROGRESS';
export const GET_SECTOR_SUCCESS = 'GET_DATA_SECTOR_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_SECTOR = 'ADD_SECTOR';
export const UPDATE_SECTOR = 'UPDATE_SECTOR';
export const DELETE_SECTOR = 'DELETE_SECTOR';
export const SEARCH_SECTOR = 'SEARCH_SECTOR';
export const CHANGE_SEARCH_SECTOR = 'CHANGE_SEARCH_SECTOR';
