export const GET_DATA_SECTOR_PROGRESS = 'GET_DATA_SECTOR_PROGRESS';
export const GET_DATA_SECTOR_SUCCESS = 'GET_DATA_SECTOR_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_SECTOR = 'ADD_SECTOR';
export const SAVE_SECTOR = 'SAVE_SECTOR';
export const EDIT_SECTOR = 'EDIT_SECTOR';
export const DELETE_SECTOR = 'DELETE_SECTOR';
export const CANCEL_SECTOR = 'CANCEL_SECTOR';
