export const GET_DATA_SECTOR_PROGRESS = 'GET_DATA_SECTOR_PROGRESS';
export const GET_DATA_SECTOR_SUCCESS = 'GET_DATA_SECTOR_SUCCESS';
export const GET_DATA_SECTOR_FAILED = 'GET_DATA_AGREEMENT_FAILED';
export const SAVE_DATA_SECTOR_PROGRESS = 'SAVE_DATA_SECTOR_PROGRESS';
export const SAVE_DATA_SECTOR_SUCCESS = 'SAVE_DATA_SECTOR_SUCCESS';
export const SAVE_DATA_SECTOR_FAILED = 'SAVE_DATA_SECTOR_FAILED';
