export const GET_CALLED_SUPPLIERS_PROGRESS = 'GET_CALLED_SUPPLIERS_PROGRESS';
export const GET_CALLED_SUPPLIERS_SUCCESS = 'GET_CALLED_SUPPLIERS_SUCCESS';

export const SEND_INVITATION_PROGRESS = 'SEND_INVITATION_PROGRESS';
export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';

export const FILTER_CALLED_SUPPLIERS = 'FILTER_CALLED_SUPPLIERS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

