export const GET_CALLED_SUPPLIERS_PROGRESS = 'GET_CALLED_SUPPLIERS_PROGRESS';
export const GET_CALLED_SUPPLIERS_SUCCESS = 'GET_CALLED_SUPPLIERS_SUCCESS';

export const SEND_INVITATION_PROGRESS = 'SEND_INVITATION_PROGRESS';
export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';

export const DELETE_SUPPLIER_BY_CALL = 'DELETE_SUPPLIER_BY_CALL';

export const FILTER_CALLED_SUPPLIERS = 'FILTER_CALLED_SUPPLIERS';
export const CLEAR_DATA_CALLED_SUPPLIERS = 'CLEAR_DATA_CALLED_SUPPLIERS';

export const GET_SUPPLIERS_BY_KEY_PROGRESS = 'GET_SUPPLIERS_BY_KEY_PROGRESS';
export const GET_SUPPLIERS_BY_KEY_SUCCESS = 'GET_SUPPLIERS_BY_KEY_SUCCESS';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';
export const AUTOCOMPLETE_SUPPLIER = 'AUTOCOMPLETE_SUPPLIER';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';

export const REQUEST_FAILED = 'REQUEST_FAILED';

