export const GET_TECHNICAL_TEAM_PROGRESS = 'GET_DATA_TECHNICAL_TEAM_PROGRESS';
export const GET_TECHNICAL_TEAM_SUCCESS = 'GET_DATA_TECHNICAL_TEAM_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_TECHNICAL_TEAM = 'ADD_TECHNICAL_TEAM';
export const SAVE_TECHNICAL_TEAM = 'SAVE_TECHNICAL_TEAM';
export const DELETE_TECHNICAL_TEAM = 'DELETE_TECHNICAL_TEAM';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
