export const GET_DATA_CALL_PROGRESS = 'GET_DATA_CALL_PROGRESS';
export const GET_DATA_CALL_SUCCESS = 'GET_DATA_CALL_SUCCESS';

export const GET_CALL_PROGRESS = 'GET_CALL_PROGRESS';
export const GET_CALL_SUCCESS = 'GET_CALL_SUCCESS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT = 'CLEAR_EDIT';
