export const GET_DATA_CALL_PROGRESS = 'GET_DATA_CALL_PROGRESS';
export const GET_DATA_CALL_SUCCESS = 'GET_DATA_CALL_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const GET_CALL_PROGRESS = 'GET_CALL_PROGRESS';
export const GET_CALL_SUCCESS = 'GET_CALL_SUCCESS';

export const GET_SUPPLIERS_BY_CALL_PROGRESS = 'GET_SUPPLIERS_BY_CALL_PROGRESS';
export const GET_SUPPLIERS_BY_CALL_SUCCESS = 'GET_SUPPLIERS_BY_CALL_SUCCESS';
export const REQUEST_SUPPLIERS_FAILED = 'REQUEST_SUPPLIERS_FAILED';
export const FILTER_SUPPLIERS = 'FILTER_SUPPLIERS';

export const SEND_INVITATION_PROGRESS = 'SEND_INVITATION_PROGRESS';
export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';

export const CLEAR_EDIT = 'CLEAR_EDIT';
