export const GET_DATA_CALL_PROGRESS = 'GET_DATA_CALL_PROGRESS';
export const GET_DATA_CALL_SUCCESS = 'GET_DATA_CALL_SUCCESS';

export const GET_CALL_PROGRESS = 'GET_CALL_PROGRESS';
export const GET_CALL_SUCCESS = 'GET_CALL_SUCCESS';

export const SEARCH_CALL = 'SEARCH_CALL';
export const CHANGE_SEARCH_CALL = 'CHANGE_SEARCH_CALL';

export const SAVE_CALL = 'SAVE_CALL';
export const DELETE_CALL = 'DELETE_CALL';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT = 'CLEAR_EDIT';
export const CHANGE_DISABLED = 'CHANGE_DISABLED';
