package com.nutresa.exemplary_provider.dtl;

public enum AlertType {
    PENDING_VALIDATION_DUE_TO_CHANGE_IN_COMPANY_SIZE,
    SURVEY_PARTIALLY_SAVED_BY_THE_PROVIDER,
    SURVEY_PARTIALLY_SAVED_BY_THE_EVALUATOR,
    PENDING_EVALUATION_BY_THE_TECHNICAL_TEAM,
    PENDING_EVALUATION_BY_THE_MANAGER_TEAM,
    SURVEY_PARTIALLY_SAVED_BY_THE_TECHNICAL_TEAM,
    SURVEY_PARTIALLY_SAVED_BY_THE_MANAGER_TEAM;
}
