package com.nutresa.exemplary_provider.dtl;

public enum HandlerGenericExceptionTypes {
    DONT_HAVE_EVALUATOR,
    INVALID_VALUE,
    UNEXPECTED_VALUE,
    INFORMATION_NOT_FOUND,
    ROL_INVALID, DOCUMENT_EXISTS,
    CALL_NOT_ESPECIFIED,
    STATE_NOT_FOUND,
    DONT_HAVE_SURVEY_ASSOCIED,
    DATE_TO_MAKE_SURVEY_EVALUATOR_EXCEEDED,
    DATE_TO_MAKE_SURVEY_EXCEEDED,
    THE_SURVEY_COULD_NOT_BE_COMPLETED;
}
