package com.nutresa.exemplary_provider.dtl;

public enum NotificationType {
    CHANGE_COMPANY_SIZE,
    CHANGE_COMPANY_SIZE_CONFIRMED,
    SUPPLIER_CALLED_BY_LIBERATOR,
    SUPPLIER_CALLED_BY_TECHNICAL_TEAM,
    SUPPLIER_CALLED_BY_MANAGER_TEAM,
    SURVEY_ENDED_BY_EVALUATOR,
    SURVEY_ENDED_BY_MANAGER_TEAM,
    SURVEY_ENDED_BY_SUPPLIER,
    SURVEY_ENDED_BY_TECHNICAL_TEAM,
    SUPPLIER_DISCARDED,
    TECHNICAL_TEAM_CALLED_BY_LIBERATOR,
    MANAGER_TEAM_CALLED_BY_LIBERATOR,
    SURVEY_FINISHED_BY_SUPPLIER;
}
