package com.nutresa.exemplary_provider.dtl;

public enum SurveyStates {
    DONT_PARTICIPATE,
    ENDED_EVALUATOR,
    ENDED_SUPPLIER,
    EVALUATOR,
    NOT_STARTED,
    NOT_STARTED_EVALUATOR,
    SUPPLIER,
    NOT_STARTED_TECHNICAL_TEAM,
    ENDED_TECHNICAL_TEAM,
    DONT_APPLY_TECHNICAL_TEAM,
    TECHNICAL_TEAM,
    DONT_APPLY_EVALUATOR;
}
