package com.nutresa.exemplary_provider.dtl;

public enum SurveyStates {
    DONT_PARTICIPATE,
    NOT_STARTED,
    SUPPLIER,
    ENDED_SUPPLIER,
    DONT_APPLY_EVALUATOR,
    NOT_STARTED_EVALUATOR,
    EVALUATOR,
    ENDED_EVALUATOR,
    DONT_APPLY_TECHNICAL_TEAM,
    NOT_STARTED_TECHNICAL_TEAM,
    TECHNICAL_TEAM,
    ENDED_TECHNICAL_TEAM,
    DONT_APPLY_MANAGER_TEAM,
    NOT_STARTED_MANAGER_TEAM,
    MANAGER_TEAM,
    ENDED_MANAGER_TEAM;
}
