export const GET_MENU_PROGRESS = 'GET_DATA_MENU_PROGRESS';
export const GET_MENU_SUCCESS = 'GET_DATA_MENU_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_MENU = 'ADD_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const SEARCH_MENU = 'SEARCH_MENU';
export const CHANGE_SEARCH_MENU = 'CHANGE_SEARCH_MENU';
