export const GET_ACCESS_PROGRESS = 'GET_DATA_ACCESS_PROGRESS';
export const GET_ACCESS_SUCCESS = 'GET_DATA_ACCESS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_ACCESS = 'ADD_ACCESS';
export const UPDATE_ACCESS = 'UPDATE_ACCESS';
export const DELETE_ACCESS = 'DELETE_ACCESS';
export const SEARCH_ACCESS = 'SEARCH_ACCESS';
export const CHANGE_SEARCH_ACCESS = 'CHANGE_SEARCH_ACCESS';
