export const GET_DATA_AGREEMENT_PROGRESS = 'GET_DATA_AGREEMENT_PROGRESS';
export const GET_DATA_AGREEMENT_SUCCESS = 'GET_DATA_AGREEMENT_SUCCESS';
export const GET_DATA_AGREEMENT_FAILED = 'GET_DATA_AGREEMENT_FAILED';
export const GET_DATA_SEARCH_AGREEMENT_SUCCESS = 'GET_DATA_SEARCH_AGREEMENT_SUCCESS';
