export const GET_DATA_GENERAL_PROGRESS = 'GET_DATA_GENERAL_PROGRESS';
export const GET_DATA_GENERAL_SUCCESS = 'GET_DATA_GENERAL_SUCCESS';

export const GET_DATA_STATISTICAL_PROGRESS = 'GET_DATA_STATISTICAL_PROGRESS';
export const GET_DATA_STATISTICAL_SUCCESS = 'GET_DATA_STATISTICAL_SUCCESS';

export const GET_DATA_CURRENT_PROGRESS = 'GET_DATA_CURRENT_PROGRESS';
export const GET_DATA_CURRENT_SUCCESS = 'GET_DATA_CURRENTL_SUCCESS';

export const REQUEST_FAILED = 'REQUEST_FAILED';

