export const GET_USER_PROGRESS = 'GET_DATA_USER_PROGRESS';
export const GET_USER_SUCCESS = 'GET_DATA_USER_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SEARCH_USER = 'SEARCH_USER';
