export const GET_DATA_SURVEYS_PROGRESS = 'GET_DATA_SURVEYS_PROGRESS';
export const GET_DATA_SURVEYS_SUCCESS = 'GET_DATA_SURVEYS_SUCCESS';
export const FILTER_SURVEYS = 'FILTER_SURVEYS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
