export const GET_DATA_GENERAL_ADMINISTRATOR_PROGRESS = 'GET_DATA_GENERAL_ADMINISTRATOR_PROGRESS';
export const GET_DATA_GENERAL_ADMINISTRATOR_SUCCESS = 'GET_DATA_GENERAL_ADMINISTRATOR_SUCCESS';

export const GET_GENERAL_ADMINISTRATOR_PROGRESS = 'GET_GENERAL_ADMINISTRATOR_PROGRESS';
export const GET_GENERAL_ADMINISTRATOR_SUCCESS = 'GET_GENERAL_ADMINISTRATOR_SUCCESS';

export const REQUEST_FAILED = 'REQUEST_FAILED';

export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT';
export const CLEAN_DATA = 'CLEAN_DATA';

export const SAVE_DATA_PROGRESS = 'SAVE_DATA_PROGRESS';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
