export const GET_DATA_GENERAL_ADMINISTRATOR_PROGRESS = 'GET_DATA_GENERAL_ADMINISTRATOR_PROGRESS';
export const GET_DATA_GENERAL_ADMINISTRATOR_SUCCESS = 'GET_DATA_GENERAL_ADMINISTRATOR_SUCCESS';

export const GET_GENERAL_ADMINISTRATOR_PROGRESS = 'GET_GENERAL_ADMINISTRATOR_PROGRESS';
export const GET_GENERAL_ADMINISTRATOR_SUCCESS = 'GET_GENERAL_ADMINISTRATOR_SUCCESS';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const CLEAR_EDIT = 'CLEAR_EDIT';
