export const GET_DATA_MODIFIED_SUPPLIERS_PROGRESS = 'GET_DATA_MODIFIED_SUPPLIERS_PROGRESS';
export const GET_DATA_MODIFIED_SUPPLIERS_SUCCESS = 'GET_DATA_MODIFIED_SUPPLIERS_SUCCESS';
export const FILTER_MODIFIED_SUPPLIERS = 'FILTER_MODIFIED_SUPPLIERS';
export const SET_COMPANY_SIZE = 'SET_COMPANY_SIZE';
export const UNLOCK_SUPPLIER_SUCCESS = 'UNLOCK_SUPPLIER_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
