export const GET_DATA_MODIFIED_SUPPLIERS_PROGRESS = 'GET_DATA_MODIFIED_SUPPLIERS_PROGRESS';
export const GET_DATA_MODIFIED_SUPPLIERS_SUCCESS = 'GET_DATA_MODIFIED_SUPPLIERS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
