export const GET_NOTIFICATION_PROGRESS = 'GET_DATA_NOTIFICATION_PROGRESS';
export const GET_NOTIFICATION_SUCCESS = 'GET_DATA_NOTIFICATION_SUCCESS';

export const GET_NOTIFICATION_BY_ID_SUCCESS = 'GET_NOTIFICATION_BY_ID_SUCCESS';
export const SAVE_NOTIFICATION = 'SAVE_NOTIFICATION';
export const CLEAN_DATA = 'CLEAN_DATA';
export const UPDATE_NOTIFICATION_ATTACHMENT = 'UPDATE_NOTIFICATION_ATTACHMENT';

export const REQUEST_FAILED = 'REQUEST_FAILED';
