export const GET_MANAGER_TEAM_PROGRESS = 'GET_DATA_MANAGER_TEAM_PROGRESS';
export const GET_MANAGER_TEAM_SUCCESS = 'GET_DATA_MANAGER_TEAM_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_MANAGER_TEAM = 'ADD_MANAGER_TEAM';
export const UPDATE_MANAGER_TEAM = 'UPDATE_MANAGER_TEAM';
export const DELETE_MANAGER_TEAM = 'DELETE_MANAGER_TEAM';
export const SEARCH_MANAGER_TEAM = 'SEARCH_MANAGER_TEAM';
export const CHANGE_SEARCH_MANAGER_TEAM = 'CHANGE_SEARCH_MANAGER_TEAM';
