export const GET_SOCIETY_TYPE_PROGRESS = 'GET_DATA_SOCIETY_TYPE_PROGRESS';
export const GET_SOCIETY_TYPE_SUCCESS = 'GET_DATA_SOCIETY_TYPE_SUCCESS';

export const ADD_SOCIETY_TYPE = 'ADD_SOCIETY_TYPE';
export const UPDATE_SOCIETY_TYPE = 'UPDATE_SOCIETY_TYPE';
export const DELETE_SOCIETY_TYPE = 'DELETE_SOCIETY_TYPE';

export const SEARCH_SOCIETY_TYPE = 'SEARCH_SOCIETY_TYPE';
export const CHANGE_SEARCH_SOCIETY_TYPE = 'CHANGE_SEARCH_SOCIETY_TYPE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
