export const GET_COMPANY_TYPE_PROGRESS = 'GET_DATA_COMPANY_TYPE_PROGRESS';
export const GET_COMPANY_TYPE_SUCCESS = 'GET_DATA_COMPANY_TYPE_SUCCESS';

export const ADD_COMPANY_TYPE = 'ADD_COMPANY_TYPE';
export const UPDATE_COMPANY_TYPE = 'UPDATE_COMPANY_TYPE';
export const DELETE_COMPANY_TYPE = 'DELETE_COMPANY_TYPE';

export const SEARCH_COMPANY_TYPE = 'SEARCH_COMPANY_TYPE';
export const CHANGE_SEARCH_COMPANY_TYPE = 'CHANGE_SEARCH_COMPANY_TYPE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
