export const GET_ACCESS_BY_ROL_PROGRESS = 'GET_DATA_ACCESS_BY_ROL_PROGRESS';
export const GET_ACCESS_BY_ROL_SUCCESS = 'GET_DATA_ACCESS_BY_ROL_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const ADD_ACCESS_BY_ROL = 'ADD_ACCESS_BY_ROL';
export const UPDATE_ACCESS_BY_ROL = 'UPDATE_ACCESS_BY_ROL';
export const DELETE_ACCESS_BY_ROL = 'DELETE_ACCESS_BY_ROL';
export const SEARCH_ACCESS_BY_ROL = 'SEARCH_ACCESS_BY_ROL';
export const CHANGE_SEARCH_ACCESS_BY_ROL = 'CHANGE_SEARCH_ACCESS_BY_ROL';
