export const GET_SUPPLIER_SELECTION_PROGRESS = 'GET_SUPPLIER_SELECTION_PROGRESS';
export const GET_SUPPLIER_SELECTION_SUCCESS = 'GET_SUPPLIER_SELECTION_SUCCESS';
export const CHECK_SUPPLIER = 'CHECK_SUPPLIER';
export const UPDATE_SUPPLIER_SELECTION = 'UPDATE_SUPPLIER_SELECTION';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const RESET_DATA = 'RESET_DATA';
export const GET_SUPPLIES_SPECIAL = 'GET_SUPPLIES_SPECIAL';
