export const GET_TECHNICAL_TEAM_SURVEY_PROGRESS = 'GET_TECHNICAL_TEAM_SURVEY_PROGRESS';
export const GET_TECHNICAL_TEAM_SURVEY_SUCCESS = 'GET_TECHNICAL_TEAM_SURVEY_SUCCESS';
export const FILTER_TECHNICAL_TEAM_SURVEY = 'FILTER_TECHNICAL_TEAM_SURVEY';
export const REQUEST_FAILED = 'REQUEST_FAILED';
