export const GET_COMPANY_SIZE_PROGRESS = 'GET_DATA_COMPANY_SIZE_PROGRESS';
export const GET_COMPANY_SIZE_SUCCESS = 'GET_DATA_COMPANY_SIZE_SUCCESS';

export const ADD_COMPANY_SIZE = 'ADD_COMPANY_SIZE';
export const UPDATE_COMPANY_SIZE = 'UPDATE_COMPANY_SIZE';
export const DELETE_COMPANY_SIZE = 'DELETE_COMPANY_SIZE';

export const SEARCH_COMPANY_SIZE = 'SEARCH_COMPANY_SIZE';
export const CHANGE_SEARCH_COMPANY_SIZE = 'CHANGE_SEARCH_COMPANY_SIZE';

export const REQUEST_FAILED = 'REQUEST_FAILED';
