export const GET_DATA_SUPPLIER_PROGRESS = 'GET_DATA_SUPPLIER_PROGRESS';
export const GET_DATA_SUPPLIER_SUCCESS = 'GET_DATA_SUPPLIER_SUCCESS';
export const GET_DATA_CATEGORIES_SUCCESS = 'GET_DATA_CATEGORIES_SUCCESS';
export const GET_DATA_SUBCATEGORIES_SUCCESS = 'GET_DATA_SUBCATEGORIES_SUCCESS';
export const GET_DATA_DEPARTMENTS_SUCCESS = 'GET_DATA_DEPARTMENTS_SUCCESS';
export const GET_DATA_CITIES_SUCCESS = 'GET_DATA_CITIES_SUCCESS';
export const SAVE_DATA_SUPPLIER_PROGRESS = 'SAVE_DATA_SUPPLIER_PROGRESS';
export const SAVE_DATA_SUPPLIER_SUCCESS = 'SAVE_DATA_SUPPLIER_SUCCESS';
export const SAVE_DATA_SUPPLIER_FAILED = 'SAVE_DATA_SUPPLIER_FAILED';
export const GET_REQUEST_FAILED = 'GET_REQUEST_FAILED';

