export const GET_DATA_SUPPLIER_PROGRESS = 'GET_DATA_SUPPLIER_PROGRESS';
export const GET_DATA_SUPPLIER_SUCCESS = 'GET_DATA_SUPPLIER_SUCCESS';
export const GET_DATA_SUPPLIER_FAILED = 'GET_DATA_AGREEMENT_FAILED';
export const SAVE_DATA_SUPPLIER_PROGRESS = 'SAVE_DATA_SUPPLIER_PROGRESS';
export const SAVE_DATA_SUPPLIER_SUCCESS = 'SAVE_DATA_SUPPLIER_SUCCESS';
export const SAVE_DATA_SUPPLIER_FAILED = 'SAVE_DATA_SUPPLIER_FAILED';

